FROM node:lts

COPY ./ /var/www/
WORKDIR /var/www/

ARG NEXT_PUBLIC_VALID_USER
ARG NEXT_PUBLIC_VALID_PASS
ARG NEXT_PUBLIC_URL_LOGS
ARG NEXT_PUBLIC_USERNAME_LOG
ARG NEXT_PUBLIC_PASS_LOG

ENV NEXT_PUBLIC_VALID_USER=${NEXT_PUBLIC_VALID_USER}
ENV NEXT_PUBLIC_VALID_PASS=${NEXT_PUBLIC_VALID_PASS}
ENV NEXT_PUBLIC_URL_LOGS=${NEXT_PUBLIC_URL_LOGS}
ENV NEXT_PUBLIC_USERNAME_LOG=${NEXT_PUBLIC_USERNAME_LOG}
ENV NEXT_PUBLIC_PASS_LOG=${NEXT_PUBLIC_PASS_LOG}

RUN npm install --force

RUN npm run build

ENTRYPOINT npm run start